### ISSUE TITLE
Misleading screenshot of finished workshop early in the workshop causes confusion

### ISSUE THREAD

**Issue by paul-snively** [quarkusio/quarkus-workshops#352]
[Running the web application](https://quarkus.io/quarkus-workshops/super-heroes/spine.html#_running_the_web_application) after following the workshop having downloaded the [linked .zip archive](https://raw.githubusercontent.com/quarkusio/quarkus-workshops/refs/heads/main/quarkus-workshop-super-heroes/dist/quarkus-super-heroes-workshop.zip) and following the workshop to that point does not show villains or heroes in the UI. I suspect this has to do with the fact that the `FightService`'s `findRandomFighters()` method is still unimplemented at this point, and in fact the `FightService` hasn't been wired up with the `VillainService` and `HeroService` at all yet.

**Comment by geoand** [comment]
Thanks for reporting @paul-snively.

I assume you have tried the absolute latest version, correct?

**Comment by holly-cummins** [comment]
Is it this bit of the workshop, near the beginning?

<img width="1166" alt="image" src="https://github.com/quarkusio/quarkus-workshops/assets/11509290/58d72b48-dbf4-460f-a8d3-45e978a4b8e9">

That's a preview of what you'll get later on, but it's caused confusion in the past, since it's not what people will have at that point in the workshop. 

I'm also looking at https://quarkus.io/quarkus-workshops/super-heroes/spine.html#_the_web_application, but I think at that point https://quarkus.io/quarkus-workshops/super-heroes/spine.html#_fightresource_endpoint should have been completed, which wires everything together.

**Comment by paul-snively** [comment]
Yep, that's exactly it. Sorry!

I took the image with the pictures to be what I should expect to see at that point. The very next section, though, explains why that isn't what you get, and walks through correcting the issue.

I would _strongly_ suggest replacing the image with correct (but not what you'll actually get) results with one like the one in the CORS section, or just removing it completely and letting the flow go naturally on to the CORS discussion.

I'll close this, since there's not actually an "issue" beyond the possibility of confusion and perhaps identifying one approach to reducing it. :-)

**Comment by holly-cummins** [comment]
You're not the first person to get confused by this, so I'm going to update the issue name but keep it open. After I spotted people getting confused I'd tried to put in extra words saying "this isn't what you get! this is just what you might get!" ... but I guess a picture outweighs a thousand words. :)

**Comment by agoncal** [comment]
We have two images: one with AI one without:

* https://github.com/quarkusio/quarkus-workshops/blob/main/quarkus-workshop-super-heroes/docs/src/docs/asciidoc/images/angular-ui-ai.png
* https://github.com/quarkusio/quarkus-workshops/blob/main/quarkus-workshop-super-heroes/docs/src/docs/asciidoc/images/angular-ui.png

**Comment by paul-snively** [comment]
Thanks so much, @geoand, @holly-cummins, and @agoncal!

I hope you'll please forgive my hijacking the thread, but I'm studying Quarkus because I have believed for some time it's the best Java framework, and after almost a decade in Scala, opportunities there seem to be drying up, so I'm seeking a role, ideally using Quarkus, where they could use an Architect/Tech Lead/Sr. Staff Engineer type with an extremely strong functional programming background, "reactive-first," etc. who might need a few weeks to re-acclimate to the Java world, but would likely find the concepts immediately transferable. So any leads to remote Quarkus opportunities friendly to the US Eastern timezone would be _greatly_ appreciated. Please feel free to message me directly here, or on Twitter at @paul_snively. Thanks so much again!

**Comment by geoand** [comment]
@paul-snively understood, if I see something, I'll point it your way :)

**Comment by holly-cummins** [comment]
Actually, reading the conversation, I don't think the screenshot I pasted above is the problem one. The one I pasted is near the top, before anything has been started. But later on, there is is this one:

<img width="1012" alt="image" src="https://github.com/quarkusio/quarkus-workshops/assets/11509290/751eb2c2-2f48-422f-b4f7-7c3dadf52f5a">

And the text below says 

> If you want, you can visit http://localhost:4200/ (the usual Angular port) to confirm that Quinoa is forwarding what’s on port 4200 to port 8080. The version of the application on http://localhost:4200/ will be disappointingly blank, because it’s looking for its config on the wrong port.

So the screenshot is definitely mis-aligned with the text, and should be fixed.

**Comment by holly-cummins** [comment]
Actually, re-reading the conversation, I think the screenshot I pasted isn't the one @paul-snively was looking at, because my screenshot is at the top of the doc, and in @paul-snively's case the section following the screenshot explains how to fix the blank screenshot. I think that screenshot is the one before the CORS section, this one: 

<img width="723" alt="image" src="https://github.com/quarkusio/quarkus-workshops/assets/11509290/97e77e51-3900-4cb6-9d55-3837f2ae96fc">
