### ISSUE TITLE
Add the extension guard when building the extension

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-workshops#374]
In the "The completed workshop" section we should build the extension only if we want to do the workshop with extension. 

We should use the extension guard for this command

```
./mvnw clean install -f super-heroes/extension-version
```

**Comment by holly-cummins** [comment]
Good spot. If we do #233, we might even be able to go further drop the whole section, since it's a bit confusing. We put lots of "when you get to the end" instructions at the beginning, and it causes a bit of confusion since people tend to follow them. 

Perhaps the section should be in a 'Reference' part that's listed in the toc but not quite so near the beginning. But all that can be a different change.
